import {
    BellIcon,
    BookIcon,
    CaretLeftIcon,
    CaretRightIcon,
    EyeClosedIcon,
    EyeIcon,
    FacebookLogoIcon,
    HouseSimpleIcon,
    InfoIcon,
    InstagramLogoIcon,
    LinkedinLogoIcon,
    MoonIcon,
    PhoneIcon,
    SignOutIcon,
    SunIcon,
    UsersIcon,
    XLogoIcon,
    YoutubeLogoIcon,
    LayoutIcon,
    GearIcon,
    ChalkboardTeacherIcon,
} from "@phosphor-icons/react/ssr";

export const Icons = {
    Teacher: ChalkboardTeacherIcon,
    Gear: GearIcon,
    Layout: LayoutIcon,
    SignOut: SignOutIcon,
    CaretLeft: CaretLeftIcon,
    CaretRight: CaretRightIcon,
    Sun: SunIcon,
    Moon: MoonIcon,
    Bell: BellIcon,
    LinkedIn: LinkedinLogoIcon,
    YouTube: YoutubeLogoIcon,
    X: XLogoIcon,
    Phone: PhoneIcon,
    Users: UsersIcon,
    Book: BookIcon,
    Info: InfoIcon,
    Eye: EyeIcon,
    EyeOff: EyeClosedIcon,
    House: HouseSimpleIcon,
    Facebook: FacebookLogoIcon,
    Instagram: InstagramLogoIcon,
};

export type IconName = keyof typeof Icons;
