import {
    BellIcon,
    BookIcon,
    CaretLeftIcon,
    CaretRightIcon,
    EyeClosedIcon,
    EyeIcon,
    FacebookLogoIcon,
    HouseSimpleIcon,
    InfoIcon,
    InstagramLogoIcon,
    LinkedinLogoIcon,
    MoonIcon,
    PhoneIcon,
    SignOutIcon,
    SunIcon,
    UsersIcon,
    XLogoIcon,
    YoutubeLogoIcon,
    LayoutIcon,
    GearIcon,
    ChalkboardTeacherIcon,
    DotsSixVerticalIcon,
    PlusCircleIcon,
    CheckIcon,
    UploadSimpleIcon,
    TrashIcon,
    FileAudioIcon,
    FileVideoIcon,
    FileTextIcon,
    FilePdfIcon,
    FileIcon,
    PencilSimpleIcon,
    DotsThreeVerticalIcon,
    PlusIcon,
    ListIcon,
    ArrowRightIcon,
    EnvelopeIcon,
    MapPinIcon,
    SparkleIcon,
    MusicNoteIcon,
    PlayIcon,
    PauseIcon,
    XIcon,
    ImageIcon,
    FolderIcon,
    StackIcon,
    RowsIcon,
    SpinnerIcon,
    CaretUpDownIcon,
    CopyIcon,
    StarIcon,
    StarHalfIcon,
} from "@phosphor-icons/react/ssr";

export const Icons = {
    List: ListIcon,
    Close: XIcon,
    Plus: PlusIcon,
    ArrowRight: ArrowRightIcon,
    Envelope: EnvelopeIcon,
    MapPin: MapPinIcon,
    Sparkle: SparkleIcon,
    MusicNote: MusicNoteIcon,
    Play: PlayIcon,
    Pause: PauseIcon,
    DotsThreeVertical: DotsThreeVerticalIcon,
    PencilSimple: PencilSimpleIcon,
    File: FileIcon,
    FilePdf: FilePdfIcon,
    FileText: FileTextIcon,
    FileAudio: FileAudioIcon,
    FileVideo: FileVideoIcon,
    Trash: TrashIcon,
    Upload: UploadSimpleIcon,
    Check: CheckIcon,
    PlusCircle: PlusCircleIcon,
    DotsSixVertical: DotsSixVerticalIcon,
    Teacher: ChalkboardTeacherIcon,
    Gear: GearIcon,
    Layout: LayoutIcon,
    SignOut: SignOutIcon,
    CaretLeft: CaretLeftIcon,
    CaretRight: CaretRightIcon,
    Sun: SunIcon,
    Moon: MoonIcon,
    Bell: BellIcon,
    LinkedIn: LinkedinLogoIcon,
    YouTube: YoutubeLogoIcon,
    X: XLogoIcon,
    Phone: PhoneIcon,
    Users: UsersIcon,
    Book: BookIcon,
    Info: InfoIcon,
    Eye: EyeIcon,
    EyeOff: EyeClosedIcon,
    House: HouseSimpleIcon,
    Facebook: FacebookLogoIcon,
    Instagram: InstagramLogoIcon,
    Image: ImageIcon,
    Folder: FolderIcon,
    Stack: StackIcon,
    Rows: RowsIcon,
    Spinner: SpinnerIcon,
    CaretUpDown: CaretUpDownIcon,
    Copy: CopyIcon,
    Star: StarIcon,
    StarHalf: StarHalfIcon,
};

export type IconName = keyof typeof Icons;
